In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cycler
from scipy import stats
import statsmodels.api as sm

In [9]:
df1 = pd.read_csv('25_Portfolios_5x5.csv')
df2 = pd.read_csv('F-F_Research_Data_Factors.csv')
df = pd.merge(df1, df2, on = 'month')
df

,month,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,...,ME4 BM5,BIG LoBM,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM,Mkt-RF,SMB,HML,RF
0,192607,3.7782,-0.4119,-1.9434,0.3530,2.0534,2.1904,2.4192,0.4926,-1.5770,...,2.4678,3.4539,6.0902,2.0266,3.1111,0.5623,2.96,-2.30,-2.87,0.22
1,192608,-2.2074,-8.7275,2.4404,0.6086,8.3968,2.1709,-1.1849,4.0084,0.4643,...,5.3422,1.0124,4.1903,2.0131,5.4849,7.7576,2.64,-1.40,4.19,0.25
2,192609,-6.2113,-0.2989,-6.1982,-1.6368,0.8649,-1.8550,-1.2618,1.0829,-3.0405,...,0.8730,-1.2906,3.6538,0.0950,-0.7487,-2.4284,0.36,-1.32,0.01,0.23
3,192610,-8.6241,-3.7532,-5.6719,5.7170,-2.5476,-1.7995,-3.2663,-5.0745,-8.0450,...,-5.3525,-2.7413,-3.0071,-2.2437,-4.6719,-5.8129,-3.24,0.04,0.51,0.32
4,192611,3.4744,6.6476,2.2634,-4.7020,0.5362,2.9051,-2.3690,3.0078,4.6649,...,1.8213,4.2946,2.5326,1.5204,3.6619,2.5636,2.53,-0.20,-0.35,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1125,202004,24.3797,20.8938,14.5475,11.4337,15.8626,19.2871,12.8404,11.9620,9.8927,...,17.7799,14.0851,13.6907,9.7413,10.4612,15.5348,13.65,2.75,-1.35,0.00
1126,202005,13.5510,6.4995,6.6352,4.2937,4.3929,10.1370,7.2505,4.0887,1.4932,...,1.9301,5.6458,5.5022,3.7983,1.1571,3.7987,5.58,2.47,-4.95,0.01
1127,202006,11.0265,2.4121,6.8074,4.4294,6.0512,5.4178,2.9359,3.6917,2.8693,...,1.8758,5.1105,-1.0308,-0.6403,-1.8727,2.1123,2.46,2.70,-2.22,0.01
1128,202007,-0.1496,1.5904,2.8232,-0.5943,4.7126,0.8484,3.6534,3.3494,1.7883,...,2.2013,7.7232,5.1651,4.3195,1.7424,2.9417,5.77,-2.22,-1.32,0.01
1129,202008,3.4670,4.6461,4.6738,5.4297,5.8220,7.6563,7.0352,4.7985,3.3776,...,3.7617,10.7908,6.4441,2.4297,2.7699,3.4831,7.62,-0.10,-3.10,0.01

In [18]:
ExcessReturns = df.iloc[:, 1:26].sub(df['RF'], axis=0)
ExcessReturns.head()

,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,ME2 BM5,...,ME4 BM1,ME4 BM2,ME4 BM3,ME4 BM4,ME4 BM5,BIG LoBM,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM
0,3.5582,-0.6319,-2.1634,0.1330,1.8334,1.9704,2.1992,0.2726,-1.7970,-0.5544,...,1.3693,1.3078,0.9669,0.0527,2.2478,3.2339,5.8702,1.8066,2.8911,0.3423
1,-2.4574,-8.9775,2.1904,0.3586,8.1468,1.9209,-1.4349,3.7584,0.2143,5.9175,...,1.0836,3.6230,1.7559,1.9206,5.0922,0.7624,3.9403,1.7631,5.2349,7.5076
2,-6.4413,-0.5289,-6.4282,-1.8668,0.6349,-2.0850,-1.4918,0.8529,-3.2705,-1.1701,...,0.8623,-0.7550,-1.9614,1.2346,0.6430,-1.5206,3.4238,-0.1350,-0.9787,-2.6584
3,-8.9441,-4.0732,-5.9919,5.3970,-2.8676,-2.1195,-3.5863,-5.3945,-8.3650,-1.6413,...,-3.6561,-2.9759,-2.3516,-3.4251,-5.6725,-3.0613,-3.3271,-2.5637,-4.9919,-6.1329
4,3.1644,6.3376,1.9534,-5.0120,0.2262,2.5951,-2.6790,2.6978,4.3549,2.4192,...,3.1348,2.0787,3.4303,4.6220,1.5113,3.9846,2.2226,1.2104,3.3519,2.2536

In [19]:
ExcessReturns.mean()

SMALL LoBM    0.590930
ME1 BM2       0.701079
ME1 BM3       0.976126
ME1 BM4       1.133700
SMALL HiBM    1.310914
ME2 BM1       0.648592
ME2 BM2       0.932340
ME2 BM3       0.965232
ME2 BM4       1.020323
ME2 BM5       1.207341
ME3 BM1       0.734463
ME3 BM2       0.909075
ME3 BM3       0.902135
ME3 BM4       1.009158
ME3 BM5       1.070979
ME4 BM1       0.750196
ME4 BM2       0.768176
ME4 BM3       0.848637
ME4 BM4       0.931901
ME4 BM5       1.007109
BIG LoBM      0.671059
ME5 BM2       0.632477
ME5 BM3       0.703012
ME5 BM4       0.639147
BIG HiBM      0.914734
dtype: float64

In [21]:
ExcessReturns.std()

SMALL LoBM    12.096670
ME1 BM2        9.797407
ME1 BM3        8.934560
ME1 BM4        8.309022
SMALL HiBM     9.235087
ME2 BM1        7.967509
ME2 BM2        7.489349
ME2 BM3        7.226929
ME2 BM4        7.407241
ME2 BM5        8.691825
ME3 BM1        7.391985
ME3 BM2        6.469296
ME3 BM3        6.483221
ME3 BM4        6.910402
ME3 BM5        8.488538
ME4 BM1        6.245028
ME4 BM2        6.077063
ME4 BM3        6.396782
ME4 BM4        6.838043
ME4 BM5        8.664193
BIG LoBM       5.338035
ME5 BM2        5.281804
ME5 BM3        5.617778
ME5 BM4        6.595687
BIG HiBM       8.550715
dtype: float64

In [25]:
ExcessReturns.mean() / ExcessReturns.std() * np.sqrt(ExcessReturns.shape[0])

SMALL LoBM    1.642138
ME1 BM2       2.405444
ME1 BM3       3.672587
ME1 BM4       4.586566
SMALL HiBM    4.771691
ME2 BM1       2.736455
ME2 BM2       4.184748
ME2 BM3       4.489698
ME2 BM4       4.630419
ME2 BM5       4.669369
ME3 BM1       3.340013
ME3 BM2       4.723695
ME3 BM3       4.677567
ME3 BM4       4.909026
ME3 BM5       4.241184
ME4 BM1       4.038122
ME4 BM2       4.249193
ME4 BM3       4.459640
ME4 BM4       4.581176
ME4 BM5       3.907399
BIG LoBM      4.225892
ME5 BM2       4.025331
ME5 BM3       4.206660
ME5 BM4       3.257469
BIG HiBM      3.596098
dtype: float64